name: shared_ecosystem_example
description: Examples for the shared_ecosystem package
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shared_ecosystem:
    path: ../

dev_dependencies:
  test: ^1.21.0